# Generated by Django 2.2.2 on 2019-06-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Bay', 'Bay'), ('Bayan', 'Bayan')], default='Bay', max_length=5),
        ),
    ]
