# Generated by Django 2.2.2 on 2019-06-14 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190614_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Dogum Tarihi'),
            preserve_default=False,
        ),
    ]
