# Generated by Django 2.2.2 on 2019-06-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='article_image',
            new_name='member_image',
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(auto_now=True, verbose_name='Dogum Tarihi'),
        ),
    ]
