# Generated by Django 2.2.2 on 2019-06-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190614_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(verbose_name='Dogum Tarihi'),
        ),
    ]
