# Generated by Django 2.2.2 on 2019-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
    ]
