# Generated by Django 2.2.2 on 2019-06-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20190615_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_image',
            new_name='image_profile',
        ),
    ]
