# Generated by Django 2.2.2 on 2019-06-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0009_auto_20190624_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image_profile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uye'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Oluşturma Tarihi')),
                ('note', models.TextField(max_length=500, verbose_name='Açıklama')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uye')),
            ],
        ),
    ]
