# Generated by Django 2.2.2 on 2019-06-29 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0010_auto_20190628_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtransaction',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trn_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingtransaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trn_member', to=settings.AUTH_USER_MODEL, verbose_name='Uye'),
        ),
    ]
