# Generated by Django 2.2.2 on 2019-06-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20190629_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi'),
        ),
    ]
