# Generated by Django 2.2.2 on 2019-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20190629_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtransaction',
            name='time',
            field=models.IntegerField(default=7, verbose_name='Saat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingtransaction',
            name='date',
            field=models.DateTimeField(verbose_name='Oluşturma Tarihi'),
        ),
    ]
