# Generated by Django 2.2.2 on 2019-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20190701_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtransaction',
            name='date',
            field=models.DateField(verbose_name='Oluşturma Tarihi'),
        ),
    ]
