# Generated by Django 2.2.2 on 2019-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20190701_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtransaction',
            name='date',
            field=models.DateTimeField(verbose_name='Oluşturma Tarihi'),
        ),
    ]
