# Generated by Django 2.2.2 on 2019-07-02 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0015_auto_20190701_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asg_member', to=settings.AUTH_USER_MODEL, verbose_name='Uye')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asg_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen')),
            ],
        ),
    ]
