# Generated by Django 2.2.2 on 2019-06-25 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_grup', models.CharField(choices=[('Uye', 'Uye'), ('Eğitmen', 'Eğitmen'), ('Yönetici', 'Yönetici')], default='Uye', max_length=10)),
                ('image_profile', models.FileField(blank=True, null=True, upload_to='member_profile_image', verbose_name='Fotoğraf Ekleyin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
